### ISSUE TITLE
cfb command with no match gives empty response

### ISSUE THREAD

**Issue by aaron-goff** [efitz11/natsgifbot#29]
STR:

1. Use !cfb command with no exact match (like !cfb umd or !cfb university)
2. See empty response from bot

**Comment by efitz11** [comment]
what is the expected output?

**Comment by aaron-goff** [comment]
Some error message.
![image](https://user-images.githubusercontent.com/38787594/50124380-6a817480-0232-11e9-87b8-6610f9c0d0fe.png)
